version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-29
    environment:
      - JAVA_OPTIONS: "-Xmx3072m -XX:+HeapDumpOnOutOfMemoryError"

aliases:
  - &assemble
    run:
      name: Assemble Project
      command: ./gradlew assembleDebug
  - &unit_tests
    run:
      name: Run Unit Tests
      command: ./gradlew :app:testDebugUnitTest
  #  Placeholder deployment task
  - &deploy_apk
    run:
      name: Deploy Release Artifact
      command: echo "Deploy release for distribution"

jobs:

  build:
    executor: android-executor
    steps:
      - checkout
      - *assemble
      - *unit_tests

  deploy:
    executor: android-executor
    steps:
      - checkout
      - *assemble
      - *deploy_apk

workflows:
  version: 2.1

  build-workflow:
    jobs:
      - build

      - pending-deployment:
          type: approval
          requires:
            - build

      - deploy:
          requires:
            - pending-deployment
