version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-29
    environment:
      - JAVA_OPTIONS: "-Xmx3072m -XX:+HeapDumpOnOutOfMemoryError"

aliases:
  - &assemble
    run:
      name: Download Dependencies
      command: ./gradlew assembleDebug
  - &unit_tests
    run:
      name: App Unit Tests
      command: ./gradlew :app:testDebugUnitTest

jobs:

  build:
    executor: android-executor
    steps:
      - checkout
      - *assemble
      - *unit_tests

workflows:
  version: 2.1

  build-workflow:
    jobs:
      - build
