version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-29
    environment:
      - JAVA_OPTIONS: "-Xmx3072m -XX:+HeapDumpOnOutOfMemoryError"

aliases:
  - &assemble
    run:
      name: Assemble Project
      command: ./gradlew assembleDebug
  - &unit_tests
    run:
      name: Run Unit Tests
      command: ./gradlew :app:testDebugUnitTest
  #  Placeholder deployment task
  - &deploy_apk
    run:
      name: Deploy Release Artifact
      command: echo "Deploy release for distribution"

slack-aliases:
  - &slack_channel_webhook
      ${CIRCLE_SLACK_WEBHOOK}
  - &notify_slack_for_approval
    slack/notify:
      color: '#400080'
      message: |
        [${CIRCLE_USERNAME}] Please check and approve Jobs to manually deploy the releases.
        https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}
      webhook: *slack_channel_webhook

jobs:

  build:
    executor: android-executor
    steps:
      - checkout
      - *assemble
      - *unit_tests

  slack-approval-link:
    executor: general-executor
    steps:
      - *notify_slack_for_approval

  deploy:
    executor: android-executor
    steps:
      - checkout
      - *assemble
      - *deploy_apk

workflows:
  version: 2.1

  build-workflow:
    jobs:
      - build

      - slack-approval-link:
          requires:
            - build

      - pending-deployment:
          type: approval
          requires:
            - build

      - deploy:
          requires:
            - pending-deployment
